Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,15 +16,19 @@ jobs:
       - run: |
           pip install -r requirements.txt
           python manage.py test taskManager
-  
-  release:
-    machine: true                                        # What is this for?
+
+  oast:
+    machine: true
     steps:
       - checkout
-      - run: |
-          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-          docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
-          docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
+
+      - run:
+          command: docker run -v $(pwd):/src --rm hysnsec/safety check -r /src/requirements.txt --json | tee oast-results.json || true
+
+      - store_artifacts:
+          path: oast-results.json
+          destination: safety-artifact
+          when: always
 
   integration:
     docker:
@@ -35,7 +39,7 @@ jobs:
           command: |
             echo "This is an integration step"
             exit 1
-          when: on_fail      # Even if the job fails, continue to the next jobs
+          when: on_fail                    # Even if the job fails, continue to the next stages
 
   prod:
     docker:
@@ -44,57 +48,21 @@ jobs:
       - checkout
       - run: echo "This is a deploy step"
 
-  artifact:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run: echo "hello" > hello.txt
-      - store_artifacts:
-          path: hello.txt
-          destination: artifact-file
-
 workflows:
   version: 2
   django:
     jobs:
-      - build:
-          filters:          # Run the job with a specific branch
-            branches:
-              only:
-                - main
+      - build
       - test:
           requires:
             - build
-          filters:
-            branches:
-              only:
-                - main
-      - release:
+      - oast:
           requires:
             - test
-          filters:
-            branches:
-              only:
-                - main
       - integration:
           requires:
-            - release
-          filters:
-            branches:
-              only:
-                - main
+            - oast
       - prod:
+          type: approval
           requires:
             - integration
-          filters:
-            branches:
-              only:
-                - main
-      - artifact:
-          requires:
-            - prod
-          filters:
-            branches:
-              only:
-                - main
